import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "@/redux/provider";
// import HeaderLogo from "@/images/HeaderLogo";
// import FooterLogo from "@/images/FooterLogo";
import Header from "@/components/general/Header";
import Footer from "@/components/general/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Header
            classList={{
              tw: ["row-start-3","flex","gap-[24px]","flex-wrap","items-center","justify-center"],
              cs: []
            }}
            logo={`/* HeaderLogo */`}
          />
          {children}
          <Footer 
            classList={{
              tw: ["row-start-3","flex","gap-[24px]","flex-wrap","items-center","justify-center"],
              cs: []
            }} 
            year={new Date().getFullYear().toString()}
            logo={`/* FooterLogo */`}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
